' VBScript to create backend directory structure for Canteras Renacimiento Admin Panel
' Save as: CreateBackend.vbs and run with: cscript.exe CreateBackend.vbs

Dim fso, basePath, dirs, i
Set fso = CreateObject("Scripting.FileSystemObject")

basePath = "c:\Users\Xavier\para proyectos web\proyecto\backend"

' Create directories
dirs = Array(basePath, basePath & "\config", basePath & "\middleware", basePath & "\routes")

For i = 0 To UBound(dirs)
    If Not fso.FolderExists(dirs(i)) Then
        fso.CreateFolder(dirs(i))
        WScript.Echo "Created: " & dirs(i)
    End If
Next

' Create .gitignore
Dim gitignoreFile
Set gitignoreFile = fso.CreateTextFile(basePath & "\.gitignore")
gitignoreFile.WriteLine("node_modules/")
gitignoreFile.WriteLine(".env")
gitignoreFile.WriteLine(".env.local")
gitignoreFile.WriteLine(".env.*.local")
gitignoreFile.WriteLine("*.log")
gitignoreFile.WriteLine("npm-debug.log*")
gitignoreFile.WriteLine("yarn-debug.log*")
gitignoreFile.WriteLine("yarn-error.log*")
gitignoreFile.WriteLine(".DS_Store")
gitignoreFile.WriteLine("dist/")
gitignoreFile.WriteLine("build/")
gitignoreFile.WriteLine(".vscode/")
gitignoreFile.WriteLine(".idea/")
gitignoreFile.Close()

' Create package.json
Dim packageFile
Set packageFile = fso.CreateTextFile(basePath & "\package.json")
packageFile.Write("{" & vbCrLf)
packageFile.Write("  ""name"": ""canteras-renacimiento-api""," & vbCrLf)
packageFile.Write("  ""version"": ""1.0.0""," & vbCrLf)
packageFile.Write("  ""description"": ""Admin API for Canteras Renacimiento""," & vbCrLf)
packageFile.Write("  ""main"": ""server.js""," & vbCrLf)
packageFile.Write("  ""scripts"": {" & vbCrLf)
packageFile.Write("    ""start"": ""node server.js""," & vbCrLf)
packageFile.Write("    ""dev"": ""nodemon server.js""" & vbCrLf)
packageFile.Write("  }," & vbCrLf)
packageFile.Write("  ""dependencies"": {" & vbCrLf)
packageFile.Write("    ""express"": ""^4.18.2""," & vbCrLf)
packageFile.Write("    ""mysql2"": ""^3.6.0""," & vbCrLf)
packageFile.Write("    ""jsonwebtoken"": ""^9.0.0""," & vbCrLf)
packageFile.Write("    ""bcryptjs"": ""^2.4.3""," & vbCrLf)
packageFile.Write("    ""dotenv"": ""^16.0.3""," & vbCrLf)
packageFile.Write("    ""cors"": ""^2.8.5""," & vbCrLf)
packageFile.Write("    ""multer"": ""^1.4.5-lts.1""," & vbCrLf)
packageFile.Write("    ""validator"": ""^13.9.0""" & vbCrLf)
packageFile.Write("  }," & vbCrLf)
packageFile.Write("  ""devDependencies"": {" & vbCrLf)
packageFile.Write("    ""nodemon"": ""^3.0.1""" & vbCrLf)
packageFile.Write("  }" & vbCrLf)
packageFile.Write("}")
packageFile.Close()

' Create .env
Dim envFile
Set envFile = fso.CreateTextFile(basePath & "\.env")
envFile.WriteLine("PORT=3001")
envFile.WriteLine("DB_HOST=localhost")
envFile.WriteLine("DB_USER=root")
envFile.WriteLine("DB_PASSWORD=")
envFile.WriteLine("DB_NAME=canterasrenacimiento")
envFile.WriteLine("JWT_SECRET=your-secret-key-change-in-production-12345abcde")
envFile.WriteLine("JWT_EXPIRE=24h")
envFile.WriteLine("NODE_ENV=development")
envFile.Close()

' Create server.js
Dim serverFile
Set serverFile = fso.CreateTextFile(basePath & "\server.js")
serverFile.Write("require('dotenv').config();" & vbCrLf)
serverFile.Write("const express = require('express');" & vbCrLf)
serverFile.Write("const cors = require('cors');" & vbCrLf)
serverFile.Write("const errorHandler = require('./middleware/errorHandler');" & vbCrLf)
serverFile.Write("const routes = require('./routes');" & vbCrLf & vbCrLf)
serverFile.Write("const app = express();" & vbCrLf)
serverFile.Write("const PORT = process.env.PORT || 3001;" & vbCrLf & vbCrLf)
serverFile.Write("// Middleware" & vbCrLf)
serverFile.Write("app.use(cors({" & vbCrLf)
serverFile.Write("  origin: 'http://localhost:4200'," & vbCrLf)
serverFile.Write("  credentials: true" & vbCrLf)
serverFile.Write("}));" & vbCrLf & vbCrLf)
serverFile.Write("app.use(express.json());" & vbCrLf)
serverFile.Write("app.use(express.urlencoded({ extended: true }));" & vbCrLf & vbCrLf)
serverFile.Write("// Routes" & vbCrLf)
serverFile.Write("app.get('/health', (req, res) => {" & vbCrLf)
serverFile.Write("  res.status(200).json({ status: 'ok' });" & vbCrLf)
serverFile.Write("});" & vbCrLf & vbCrLf)
serverFile.Write("app.use('/api', routes);" & vbCrLf & vbCrLf)
serverFile.Write("// Error handling middleware (must be last)" & vbCrLf)
serverFile.Write("app.use(errorHandler);" & vbCrLf & vbCrLf)
serverFile.Write("// Start server" & vbCrLf)
serverFile.Write("app.listen(PORT, () => {" & vbCrLf)
serverFile.Write("  console.log(`Server running on port ${PORT}`);" & vbCrLf)
serverFile.Write("  console.log(`Environment: ${process.env.NODE_ENV}`);" & vbCrLf)
serverFile.Write("});")
serverFile.Close()

' Create config/database.js
Dim dbFile
Set dbFile = fso.CreateTextFile(basePath & "\config\database.js")
dbFile.Write("const mysql = require('mysql2/promise');" & vbCrLf & vbCrLf)
dbFile.Write("const pool = mysql.createPool({" & vbCrLf)
dbFile.Write("  host: process.env.DB_HOST || 'localhost'," & vbCrLf)
dbFile.Write("  user: process.env.DB_USER || 'root'," & vbCrLf)
dbFile.Write("  password: process.env.DB_PASSWORD || ''," & vbCrLf)
dbFile.Write("  database: process.env.DB_NAME || 'canterasrenacimiento'," & vbCrLf)
dbFile.Write("  waitForConnections: true," & vbCrLf)
dbFile.Write("  connectionLimit: 10," & vbCrLf)
dbFile.Write("  queueLimit: 0," & vbCrLf)
dbFile.Write("  enableKeepAlive: true," & vbCrLf)
dbFile.Write("  keepAliveInitialDelayMs: 0" & vbCrLf)
dbFile.Write("});" & vbCrLf & vbCrLf)
dbFile.Write("pool.on('error', (err) => {" & vbCrLf)
dbFile.Write("  console.error('Database pool error:', err);" & vbCrLf)
dbFile.Write("});" & vbCrLf & vbCrLf)
dbFile.Write("module.exports = pool;")
dbFile.Close()

' Create config/jwt.js
Dim jwtFile
Set jwtFile = fso.CreateTextFile(basePath & "\config\jwt.js")
jwtFile.Write("const jwt = require('jsonwebtoken');" & vbCrLf & vbCrLf)
jwtFile.Write("const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key-change-in-production-12345abcde';" & vbCrLf)
jwtFile.Write("const JWT_EXPIRE = process.env.JWT_EXPIRE || '24h';" & vbCrLf & vbCrLf)
jwtFile.Write("const signToken = (payload) => {" & vbCrLf)
jwtFile.Write("  return jwt.sign(payload, JWT_SECRET, {" & vbCrLf)
jwtFile.Write("    expiresIn: JWT_EXPIRE" & vbCrLf)
jwtFile.Write("  });" & vbCrLf)
jwtFile.Write("};" & vbCrLf & vbCrLf)
jwtFile.Write("const verifyToken = (token) => {" & vbCrLf)
jwtFile.Write("  try {" & vbCrLf)
jwtFile.Write("    return jwt.verify(token, JWT_SECRET);" & vbCrLf)
jwtFile.Write("  } catch (error) {" & vbCrLf)
jwtFile.Write("    throw new Error('Invalid or expired token');" & vbCrLf)
jwtFile.Write("  }" & vbCrLf)
jwtFile.Write("};" & vbCrLf & vbCrLf)
jwtFile.Write("const decodeToken = (token) => {" & vbCrLf)
jwtFile.Write("  return jwt.decode(token);" & vbCrLf)
jwtFile.Write("};" & vbCrLf & vbCrLf)
jwtFile.Write("module.exports = {" & vbCrLf)
jwtFile.Write("  signToken," & vbCrLf)
jwtFile.Write("  verifyToken," & vbCrLf)
jwtFile.Write("  decodeToken," & vbCrLf)
jwtFile.Write("  JWT_SECRET," & vbCrLf)
jwtFile.Write("  JWT_EXPIRE" & vbCrLf)
jwtFile.Write("};")
jwtFile.Close()

' Create middleware/errorHandler.js
Dim errorFile
Set errorFile = fso.CreateTextFile(basePath & "\middleware\errorHandler.js")
errorFile.Write("const errorHandler = (err, req, res, next) => {" & vbCrLf)
errorFile.Write("  console.error('Error:', err.message);" & vbCrLf)
errorFile.Write("  console.error('Stack:', err.stack);" & vbCrLf & vbCrLf)
errorFile.Write("  const status = err.status || err.statusCode || 500;" & vbCrLf)
errorFile.Write("  const message = err.message || 'Internal Server Error';" & vbCrLf & vbCrLf)
errorFile.Write("  res.status(status).json({" & vbCrLf)
errorFile.Write("    success: false," & vbCrLf)
errorFile.Write("    status," & vbCrLf)
errorFile.Write("    message," & vbCrLf)
errorFile.Write("    ...(process.env.NODE_ENV === 'development' && { stack: err.stack })" & vbCrLf)
errorFile.Write("  });" & vbCrLf)
errorFile.Write("};" & vbCrLf & vbCrLf)
errorFile.Write("module.exports = errorHandler;")
errorFile.Close()

' Create middleware/auth.js
Dim authFile
Set authFile = fso.CreateTextFile(basePath & "\middleware\auth.js")
authFile.Write("const { verifyToken } = require('../config/jwt');" & vbCrLf & vbCrLf)
authFile.Write("const auth = (req, res, next) => {" & vbCrLf)
authFile.Write("  try {" & vbCrLf)
authFile.Write("    const authHeader = req.headers.authorization;" & vbCrLf & vbCrLf)
authFile.Write("    if (!authHeader) {" & vbCrLf)
authFile.Write("      return res.status(401).json({" & vbCrLf)
authFile.Write("        success: false," & vbCrLf)
authFile.Write("        message: 'No authorization header provided'" & vbCrLf)
authFile.Write("      });" & vbCrLf)
authFile.Write("    }" & vbCrLf & vbCrLf)
authFile.Write("    const token = authHeader.startsWith('Bearer ') " & vbCrLf)
authFile.Write("      ? authHeader.slice(7) " & vbCrLf)
authFile.Write("      : authHeader;" & vbCrLf & vbCrLf)
authFile.Write("    if (!token) {" & vbCrLf)
authFile.Write("      return res.status(401).json({" & vbCrLf)
authFile.Write("        success: false," & vbCrLf)
authFile.Write("        message: 'No token provided'" & vbCrLf)
authFile.Write("      });" & vbCrLf)
authFile.Write("    }" & vbCrLf & vbCrLf)
authFile.Write("    const decoded = verifyToken(token);" & vbCrLf)
authFile.Write("    req.user = decoded;" & vbCrLf)
authFile.Write("    next();" & vbCrLf)
authFile.Write("  } catch (error) {" & vbCrLf)
authFile.Write("    return res.status(401).json({" & vbCrLf)
authFile.Write("      success: false," & vbCrLf)
authFile.Write("      message: 'Invalid or expired token'" & vbCrLf)
authFile.Write("    });" & vbCrLf)
authFile.Write("  }" & vbCrLf)
authFile.Write("};" & vbCrLf & vbCrLf)
authFile.Write("module.exports = auth;")
authFile.Close()

' Create middleware/validateInput.js
Dim validateFile
Set validateFile = fso.CreateTextFile(basePath & "\middleware\validateInput.js")
validateFile.Write("const validateInput = (schema) => {" & vbCrLf)
validateFile.Write("  return (req, res, next) => {" & vbCrLf)
validateFile.Write("    if (!schema) {" & vbCrLf)
validateFile.Write("      return next();" & vbCrLf)
validateFile.Write("    }" & vbCrLf & vbCrLf)
validateFile.Write("    const errors = {};" & vbCrLf & vbCrLf)
validateFile.Write("    for (const [field, rules] of Object.entries(schema)) {" & vbCrLf)
validateFile.Write("      const value = req.body[field];" & vbCrLf & vbCrLf)
validateFile.Write("      if (rules.required && (!value || (typeof value === 'string' && value.trim() === ''))) {" & vbCrLf)
validateFile.Write("        errors[field] = `${field} is required`;" & vbCrLf)
validateFile.Write("        continue;" & vbCrLf)
validateFile.Write("      }" & vbCrLf & vbCrLf)
validateFile.Write("      if (rules.type && value !== undefined && typeof value !== rules.type) {" & vbCrLf)
validateFile.Write("        errors[field] = `${field} must be of type ${rules.type}`;" & vbCrLf)
validateFile.Write("      }" & vbCrLf & vbCrLf)
validateFile.Write("      if (rules.minLength && value && value.length < rules.minLength) {" & vbCrLf)
validateFile.Write("        errors[field] = `${field} must be at least ${rules.minLength} characters`;" & vbCrLf)
validateFile.Write("      }" & vbCrLf & vbCrLf)
validateFile.Write("      if (rules.maxLength && value && value.length > rules.maxLength) {" & vbCrLf)
validateFile.Write("        errors[field] = `${field} must be at most ${rules.maxLength} characters`;" & vbCrLf)
validateFile.Write("      }" & vbCrLf & vbCrLf)
validateFile.Write("      if (rules.pattern && value && !rules.pattern.test(value)) {" & vbCrLf)
validateFile.Write("        errors[field] = `${field} has invalid format`;" & vbCrLf)
validateFile.Write("      }" & vbCrLf)
validateFile.Write("    }" & vbCrLf & vbCrLf)
validateFile.Write("    if (Object.keys(errors).length > 0) {" & vbCrLf)
validateFile.Write("      return res.status(400).json({" & vbCrLf)
validateFile.Write("        success: false," & vbCrLf)
validateFile.Write("        message: 'Validation failed'," & vbCrLf)
validateFile.Write("        errors" & vbCrLf)
validateFile.Write("      });" & vbCrLf)
validateFile.Write("    }" & vbCrLf & vbCrLf)
validateFile.Write("    next();" & vbCrLf)
validateFile.Write("  };" & vbCrLf)
validateFile.Write("};" & vbCrLf & vbCrLf)
validateFile.Write("module.exports = validateInput;")
validateFile.Close()

' Create routes/index.js
Dim routesFile
Set routesFile = fso.CreateTextFile(basePath & "\routes\index.js")
routesFile.Write("const express = require('express');" & vbCrLf)
routesFile.Write("const router = express.Router();" & vbCrLf & vbCrLf)
routesFile.Write("// Health check endpoint" & vbCrLf)
routesFile.Write("router.get('/health', (req, res) => {" & vbCrLf)
routesFile.Write("  res.status(200).json({" & vbCrLf)
routesFile.Write("    success: true," & vbCrLf)
routesFile.Write("    message: 'API is running'" & vbCrLf)
routesFile.Write("  });" & vbCrLf)
routesFile.Write("});" & vbCrLf & vbCrLf)
routesFile.Write("// Route placeholders for future implementation" & vbCrLf)
routesFile.Write("// Import and use routes here as they are created:" & vbCrLf)
routesFile.Write("// const authRoutes = require('./auth');" & vbCrLf)
routesFile.Write("// const userRoutes = require('./users');" & vbCrLf)
routesFile.Write("// const settingsRoutes = require('./settings');" & vbCrLf)
routesFile.Write("// " & vbCrLf)
routesFile.Write("// router.use('/auth', authRoutes);" & vbCrLf)
routesFile.Write("// router.use('/users', userRoutes);" & vbCrLf)
routesFile.Write("// router.use('/settings', settingsRoutes);" & vbCrLf & vbCrLf)
routesFile.Write("module.exports = router;")
routesFile.Close()

WScript.Echo "✓ Backend setup completed successfully!"
WScript.Echo "✓ All files created at: " & basePath
WScript.Echo ""
WScript.Echo "Next steps:"
WScript.Echo "1. cd backend"
WScript.Echo "2. npm install"
WScript.Echo "3. npm run dev"
